FROM rust:1-alpine

WORKDIR /usr/apps/binder-server

ENV BINDER_ADDRESS=${BINDER_ADDRESS}
ENV DATABASE_URL=${DATABASE_URL}
ENV MAIN_CONTAINER_LIMIT=${MAIN_CONTAINER_LIMIT}
ENV MAIN_CONTAINER_PATH=${MAIN_CONTAINER_PATH}
ENV BINDER_STORAGE_TOKEN=${BINDER_STORAGE_TOKEN}
ENV BINDER_UPLOAD_LIMIT=${BINDER_UPLOAD_LIMIT}
ENV RUST_ENV="production"

COPY target/release/ target/

CMD [ "./target/binder-server" ]