[package]
name = "binder-fm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binder-entities = { path = "../binder-entities" }
binder-utils = { path = "../binder-utils" }